-- Esquema base, sin constraints (FKs/índices se agregan en 03_constraints.sql
-- una vez cargados los datos, ver nota al final de ese archivo).

CREATE TABLE stats (
    id         INTEGER NOT NULL,
    identifier TEXT
);

CREATE TABLE moves (
    id         INTEGER NOT NULL,
    identifier TEXT,
    power      INTEGER,
    pp         INTEGER
);

CREATE TABLE pokemon (
    id              INTEGER NOT NULL,
    identifier      TEXT,
    base_experience INTEGER
);

CREATE TABLE pokemon_stat (
    pokemon_id INTEGER,
    stat_id    INTEGER,
    base_stat  INTEGER
);

CREATE TABLE pokemon_moves (
    pokemon_id INTEGER,
    move_id    INTEGER,
    level      INTEGER
);

-- TODO: tabla cargada con datos (ver 02_load.sql) pero todavía sin usar desde
-- Java — el sistema de evolución de Pokémon no está implementado.
CREATE TABLE pokemon_evolution (
    id                 INTEGER,
    pokemon_id         INTEGER,
    evolved_species_id INTEGER,
    minimum_level      INTEGER
);

CREATE TABLE player (
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name    VARCHAR(50),
    gender  VARCHAR(10)
);

CREATE TABLE player_pokemon (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY,
    player_id  INTEGER,
    pokemon_id INTEGER,
    level      INTEGER,
    current_hp INTEGER,
    team_slot  INTEGER
);
